export default [{
    text: 'h1',
    attrs: {},
    format: 'heading-one'
}, {
    text: 'h2',
    attrs: {},
    format: 'heading-two'
}, {
    text: 'h3',
    attrs: {},
    format: 'heading-three'
}, {
    text: 'Text',
    attrs: {},
    format: 'paragraph'
}, {
    text: 'Image',
    attrs: {},
    format: 'addImage'
}, {
    text: 'Quote',
    attrs: {},
    format: 'block-quote'
}, {
    text: 'Table',
    attrs: {},
    format: 'table'
}]